[package]
name = "chopsticks-executor"
version = "0.6.6"
description = "Chopsticks executor"
repository = "https://github.com/AcalaNetwork/chopsticks"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.7.2"
getrandom = { version = "0.2", default-features = false, features = ["js"] }
serde = { version = "1.0.151", default-features = false }
serde_json = { version = "1.0", default-features = false }
hex = { version = "0.4.3", default-features = false }
hex-literal = "0.4.1"
hashbrown = { version = "0.14.0", default-features = false }
wasm-bindgen = "0.2.87"
serde-wasm-bindgen = "0.5.0"
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"
log = "0.4.19"
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", optional = true }

smoldot = { path = '../vendor/smoldot/lib', default-features = false }

[features]
default = []
std = [
    "smoldot/std"
]
logging = [
	"console_log"
]

[profile.release]
codegen-units = 1
lto = true
